language: rust
cache: cargo
env:
  - FEATURES=unicorn
  - FEATURES=fake-unicorn
script:
  - cargo build --verbose --no-default-features --features=${FEATURES}
  - cargo test --verbose --no-default-features --features=${FEATURES}
