language: rust
cache: cargo
rust:
  - stable
  - nightly
env:
  - FEATURES=unicorn
  - FEATURES=fake-unicorn
before_script:
  - |
      if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then
        cargo install --force clippy && export CLIPPY=true || export CLIPPY=false ;
      fi
  - export PATH=$PATH:~/.cargo/bin
script:
  - cargo build --verbose --no-default-features --features=${FEATURES}
  - |
      if [[ "${TRAVIS_RUST_VERSION}" == "nightly" && ${CLIPPY} ]]; then
        cargo clippy
      fi
  - cargo test --verbose --no-default-features --features=${FEATURES}
